draw_config:
  key_w: 60
  key_h: 56
  split_gap: 30.0
  combo_w: 28
  combo_h: 26
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 2
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0.0
    rel_y: 4.0
    rel_w: 12.0
    rel_h: 12.0
    rx: 4.0
    ry: 4.0
  svg_extra_style: ""
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&switch_lng": { t: $$mdi:translate$$, h: Lang Switch }
    "&caps_word": { t: $$mdi:caps-lock$$, h: Caps Word }
    "&arrow_fn": =>
    "&kp LC(LEFT)": Prev Word
    "&kp LC(RIGHT)": Next Word
    "&kp LC(LG(LEFT))": Prev Desk
    "&kp LC(LG(RIGHT))": Next Desk
    "&kp LC(Z)": { t: $$mdi:undo$$, h: Undo }
    "&kp LC(Y)": { t: $$mdi:redo$$, h: Redo }
    "&kp LC(X)": { t: $$mdi:content-cut$$, h: Cut }
    "&kp LC(INS)": { t: $$mdi:content-copy$$, h: Copy }
    "&kp LS(INS)": { t: $$mdi:content-paste$$, h: Paste }
    "&kp LA(SPACE)": (K)Runner
    "&kp LG(TAB)": Desk Overview
    "&mkp MB1": { t: $$mdi:mouse-left-click$$ }
    "&mkp MB2": { t: $$mdi:mouse-right-click$$ }
    "&mkp MB3": { t: $$mdi:mouse-scroll-wheel$$ }
    "&mmv MOVE_LEFT": { t: $$mdi:chevron-left$$, h: $$mdi:mouse$$ }
    "&mmv MOVE_RIGHT": { t: $$mdi:chevron-right$$, h: $$mdi:mouse$$ }
    "&mmv MOVE_UP": { t: $$mdi:chevron-up$$, h: $$mdi:mouse$$ }
    "&mmv MOVE_DOWN": { t: $$mdi:chevron-down$$, h: $$mdi:mouse$$ }
    "&msc SCRL_LEFT": { t: $$mdi:chevron-double-left$$, h: $$mdi:mouse$$ }
    "&msc SCRL_RIGHT": { t: $$mdi:chevron-double-right$$, h: $$mdi:mouse$$ }
    "&msc SCRL_UP": { t: $$mdi:chevron-double-up$$, h: $$mdi:mouse$$ }
    "&msc SCRL_DOWN": { t: $$mdi:chevron-double-down$$, h: $$mdi:mouse$$ }
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: "{mods} + {key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
    - KC_
  qmk_keycode_map:
    XXXXXXX: ""
    "NO": ""
    MINUS: "-"
    MINS: "-"
    EQUAL: "="
    EQL: "="
    LEFT_BRACKET: "["
    LBRC: "["
    RIGHT_BRACKET: "]"
    RBRC: "]"
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: "#"
    NUHS: "#"
    SEMICOLON: ;
    SCLN: ;
    QUOTE: "'"
    QUOT: "'"
    GRAVE: "`"
    GRV: "`"
    COMMA: ","
    COMM: ","
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: "~"
    TILD: "~"
    EXCLAIM: "!"
    EXLM: "!"
    AT: "@"
    HASH: "#"
    DOLLAR: $
    DLR: $
    PERCENT: "%"
    PERC: "%"
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: "&"
    AMPR: "&"
    ASTERISK: "*"
    ASTR: "*"
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: "{"
    LCBR: "{"
    RIGHT_CURLY_BRACE: "}"
    RCBR: "}"
    PIPE: "|"
    COLON: ":"
    COLN: ":"
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: ">"
    RABK: ">"
    GT: ">"
    QUESTION: "?"
    QUES: "?"
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    # custom keys

    # media
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_VOLUME_DOWN: $$mdi:volume-medium$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_MUTE: $$mdi:volume-mute$$

    # keyboard
    SPACE: $$mdi:keyboard-space$$
    BSPC: $$mdi:backspace$$
    BACKSPACE: $$mdi:backspace$$
    RET: $$mdi:keyboard-return$$
    ENTER: $$mdi:keyboard-return$$
    TAB: $$mdi:keyboard-tab$$
    DEL: $$mdi:backspace-reverse$$
    UP: $$mdi:menu-up$$
    DOWN: $$mdi:menu-down$$
    LEFT: $$mdi:menu-left$$
    LEFT_ARROW: $$mdi:menu-left$$
    RIGHT: $$mdi:menu-right$$
    LGUI: $$mdi:microsoft-windows$$
    LMETA: $$mdi:microsoft-windows$$
    RGUI: $$mdi:microsoft-windows$$
    LALT: LAlt
    RALT: RAlt
    RSHIFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$

    #default keys
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
  zmk_combos: {}
