CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Enable OLED display
CONFIG_ZMK_DISPLAY=y

# Enable encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Keyboard sleep
CONFIG_ZMK_SLEEP=y

# Enable mouse
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Enable generic desktop usages
# CONFIG_ZMK_HID_GENERIC_DESKTOP_USAGES_BASIC=y

# Bluetooth tweaks 
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Better bluetooth connectivity
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enabling battery reporting from periferal half
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
